version: '3.8'

services:
  wordpress-honeypot:
    build: .
    ports:
      - "8080:80"
    environment:
      HONEYPOT_TYPE: wordpress
      HONEYPOT_PORT: 80
      HONEYPOT_MONGO_URL: "mongodb://root:secret@mongo:27017/dbname?authSource=admin"
      HONEYPOT_MONGO_COLLECTION: "honeypot_data"
    depends_on:
      - mongo
    volumes:
      - ./logs/wordpress:/app/logs
    logging:
      driver: "json-file"

  play-honeypot:
    build: .
    ports:
      - "8081:80"
    environment:
      HONEYPOT_TYPE: play
      HONEYPOT_PORT: 80
      HONEYPOT_MONGO_URL: "mongodb://root:secret@mongo:27017/dbname?authSource=admin"
      HONEYPOT_MONGO_COLLECTION: "honeypot_data"
    depends_on:
      - mongo
    volumes:
      - ./logs/play:/app/logs
    logging:
      driver: "json-file"

  phpmyadmin-honeypot:
    build: .
    ports:
      - "8082:80"
    environment:
      HONEYPOT_TYPE: phpmyadmin
      HONEYPOT_PORT: 80
      HONEYPOT_MONGO_URL: "mongodb://root:secret@mongo:27017/dbname?authSource=admin"
      HONEYPOT_MONGO_COLLECTION: "honeypot_data"
    depends_on:
      - mongo
    volumes:
      - ./logs/phpmyadmin:/app/logs
    logging:
      driver: "json-file"

  mikrotik-honeypot:
    build: .
    ports:
      - "8083:80"
    environment:
      HONEYPOT_TYPE: mikrotik
      HONEYPOT_PORT: 80
      HONEYPOT_MONGO_URL: "mongodb://root:secret@mongo:27017/dbname?authSource=admin"
      HONEYPOT_MONGO_COLLECTION: "honeypot_data"
    depends_on:
      - mongo
    volumes:
      - ./logs/mikrotik:/app/logs
    logging:
      driver: "json-file"

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo_data:/data/db

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - ./logs:/var/log/honeypots
      - ./promtail-config.yml:/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:10.2.2
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  mongo_data:
  grafana-storage:
