version: '3.8'

services:
  web-honeypot:
    build: .
    ports:
      - "80:80"
    environment:
      HONEYPOT_PORT: 80
      HONEYPOT_MONGO_URL: "mongodb://root:secret@mongo:27017/dbname?authSource=admin"
      HONEYPOT_MONGO_COLLECTION: "honeypot_data"
    depends_on:
      - mongo
    volumes:
      - ./logs:/app/logs
    logging:
      driver: "json-file"

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo_data:/data/db

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - ./logs:/var/log
      - ./promtail-config.yml:/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:10.2.2
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  mongo_data:
  grafana-storage: