auth_enabled: false
server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

limits_config:
  allow_structured_metadata: false  # Kluczowa zmiana!

schema_config:
  configs:
    - from: "2024-01-01"
      store: tsdb  # Nowy typ indeksu
      object_store: filesystem
      schema: v13  # Wymagany schemat
      index:
        prefix: index_
        period: 24h